########################################################################
# housekeeping
########################################################################

use v5.12;
use strict;
use FindBin::libs;

use Test::More;

use WCurve::Test::RandomDNA;

use WCurve;

########################################################################
# package variables
########################################################################

my $verbose = $ENV{ VERBOSE } || '';

my $base_seq
= do
{
    local $/;

    $a  = <DATA>;

    $b  = index $a, "\n";

    substr $a, 0, $b, '';

    $a  =~ s{ \W+ }{}xg;

    lc $a
};

my @testz = 
(
    [  0, 0, '',            0                       ],
    [  0, 3, 'TGA',         0.000749669233339085    ], # SNP
    [ -1, 0, 'CATG',        0.00233641052872084     ], # trailing gap
    [ 100, 0, 'CATGCATG',   0.00630329944575486     ], # internal gap
);

my $limit   = 0.000000000000001;

plan tests => scalar @testz;

########################################################################
# utility subs
########################################################################

########################################################################
# run test
########################################################################

my $wc0 = WCurve->new( Floating => Base => $base_seq );

my $alt_seq = $base_seq;

for( @testz )
{
    my ( $off, $len, $sub, $expect ) = @$_;

    substr $alt_seq, $off, $len, $sub;

    my $wc1     = $wc0->new( "@$_" => $alt_seq );

    my $chunkz  = $wc0->compare( matching_peaks => $wc1, 0.50, $verbose );

    my $found   = $wc0->score( SimpleTotal => $chunkz );

    my $diff    = abs( $found - $expect );

    ok $limit > $diff,  "Value is: $found ($diff)";
}

# this is not a module

0

__DATA__
> EF575362 2516 HIV-1 isolate DM1_34 from Uganda truncated envelope glycoprotein (pol) gene, complete cds.
ATGAGAGCGAGGGAGATGAAGAGGAATTGTCAGCACTTGTGGAGATGGGGCACCATGCTCCTTGGAATGTTGATGATATG
TAATGTTACAGGACAGCTGTGGGTCACAGTGTATTATGGGGTACCTGTGTGGAAAGAAGCAACCACTACTCTGTTTTGTG
CATCAGATGCTAAATCATACAAAGCAGAGGCACATAATATCTGGGCAACACATGCCTGTGTACCAACAGACCCCAACCCA
CAAGAAATGAAACTAGAAAATGTCACAGAGGACTTTAACATGTGGAAAAATAACATGGTAGAGCAAATGCATGAGGATAT
AATCAGTTTATGGGATCAAAGCCTAAAACCATGTGTAAAATTAACCCCACTCTGTGTCACTTTAAACTGCACTGAATGGA
GGAATGACACTGCCACTAATGTCACTAATGAAATGGAAATGAAAAACTGCTCTTTCAATATAACCACAGCAATAAGAGAT
AGGAAGCAGCAAGTACATGCACTTTTTTATAGAATTGATGTAGTACCAATAGATGATAATAATAGTACTAATACCAGCTA
TAGATTAATAAATTGTAATACCTCAGCCATTACACAGGCATGTCCAAAGGTATCCTTTGAACCAATTCCCATACATTATT
GTGCCCCAGCTGGATTTGCAATTCTAAAATGTAACGAGAAGAAGTTCAATGGGACGGGTCCATGCAGCAACGTTAGCACA
GTACGGTGTACTCATGGGATTAAGCCGGTAGTGTCAACTCAATTGTTGTTGAATGGCAGTCTAGCAGAAGAAGAGATAGT
AATTAGATCTGAAAATCTCACAAATAATGCTAAAATCATAATAGTACAGCTTAATCAGTCTGTAACAATTAATTGCTCAA
GGCCCTACAACATTAGAAGACAAAGGACAAGTATAGGACAAGGGCAAGCATTCCATACTCACCTAAAAATAACAGGAGAC
ATAAGACAAGCATATTGTAAGATTAATGGAACAGAATGGAATAACACCTTACAACAGGTAGCTAAAAAATTAGGAGACCT
GCTGAACAAGACAACAATAATTTTTAAACCATCCTCAGGAGGGGACCCAGAAATTACAACACATAGCTTTAATTGTGGAG
GGGAGTTTTTCTACTGCAACACATCAGGGCTATTTAATGGTACATGGAAAAATAATACATTAAGTGGCACACAGCTAAAT
GGTACAATCAAACTCCCATGCAGAATAAAACAAATTATAAACATGTGGCAAGAAGTAGGAAAAGCAATGTATGCCCCTCC
CATTGAAGGATCAATCAATTGTTCATCAAATATTACAGGACTATTGTTGGTAAGAGATGGTGGTAATGATACTAGTCAGA
ATGAGACCTTCAGACCTGGAGGAGGAGATATGAGAGACAATTGGAGAAGTGAATTATACAAATATAAGGTAGTAAGAATT
GAACCACTAGGTCTAGCACCCACCAGGGCAAAAAGAAGAGTGGTGGAAAGAGAAAAAAGAGCAATAGGACTGGGAGCTGT
GTTCCTCGGGTTCTTGGGAGCAGCAGGAAGCACAATGGGCGCAGCGTCGATAACGCTGACGGTACAGGCCAGACAGTTAC
TGTCTGGTGTAGTGCAGCAGCAAAACAATTTGCTGAGGGCTATAGAGGCGCAACAGCATCTGTTGCAACTCACAGTCTGG
GGCATTAAACAGCTCCAGGCAAGAGTCCTAGCTGTGGAAAGGTACTTAAAGGATCAACAGCTCCTAGGAATTTGGGGTTG
CTCTGGAAAACTCATTTGCACCACTACTGTGCCCTGGAACTCTAGCTGGAGTAATAAATCTCTAGAGGCGATTTGGGATA
ACATGACCTGGATGGAGTGGGAAAGAGAAATTGACAATTACACAAACTTAATATATAGCTTAATTGAAGAATCGCAAATC
CAGCAAGAAAAGAATGAACAAGAGCTATTGGAATTGGACAAATGGGCAAGTTTGTGGAATTGGTTTAACATAACACAATG
GCTGTGGTATATAAAAATATTCATAATGATAGTAGGAGGCTTGATAGGTTTAAGAATAGTTTTTGCTGTGCTTTCTTTAG
TAAATAGAGTTAGGCAGGGATACTCACCTCTGTCGTTTCAGACCCTTACCCCAGCTCCGAGGGGACCCGACAGGCCCGAA
GGAATAGAAGAAGAAGGTGGCGAGCAAGACAGAGGCAGATCCATTCGATTGGTGAACGGATTATCAGCACTTATCTGGGA
CGATCTGAGGAACCTGTGCCTCTTCAGCTACCACCACTTGAGAGACTTAATCTTAATTGCAACGAGGATTGTGGAACTTC
TGGGACGCAGGGGGTGGGAAGCCCTCAAGTATCTGTGGAATCTCCTGCAGTATTGGATCCAGGAACTAAAGAATAGCGCT
GTTAGCCTGTTGGATACCATAGCAATAGCAGTAGCTGAGGGGACAGATAGGATTATAGAAATAGTGCAAGGAATTATTAG
AGCTTAAGACAGGGCTTGGAAAGGGCTTTGCTATAA
